twitter_clone/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/users', to: 'users#show', as: 'user'
  get 'users/:id', to: 'users#show', as: 'show_user'
  post '/users/:id/follow', to: 'users#follow', as: 'follow_user'
  post 'users/:id/unfollow', to: 'users#unfollow', as: 'unfollow_user'

  get '/users/:id/followers', to: 'users#followers', as: 'followers_list'
  get '/users/:id/followees', to: 'users#followees', as: 'followees_list'

  get 'users/:id/follow_another_user', to: 'users#follow_another_user', as: 'follow_another'
  post 'users/:id/follow_another_user', to: 'users#follow_another_user', as: 'follow_another_new'

  resources :tweets
  root to: 'home#index'
end

twitter_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

twitter_clone/app/models/follow.rb
# frozen_string_literal: true

# follow model: giving permissions to follow and being followed
class Follow < ApplicationRecord
  # the user following another user
  belongs_to :follower, class_name: 'User'
  # the user being followed
  belongs_to :followee, class_name: 'User'

  validates :follower_id, uniqueness: { scope: :followee_id }
  validates :followee_id, uniqueness: { scope: :follower_id }
end

twitter_clone/app/models/tweet.rb
# frozen_string_literal: true

# tweet model: validations and permissions
class Tweet < ApplicationRecord
  belongs_to :user

  validates :tweet, presence: true,
                    length: { maximum: 280 }
end

twitter_clone/app/models/user.rb
# frozen_string_literal: true

# user model validations and permissions
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweet, dependent: :destroy
  # return an array of follows for the given user instance
  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  # return an array of users who follow the user instance
  has_many :followees, through: :followed_users
  # returns an array of follows a user gave to someone else
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  # returns an array of other users who the user has followed
  has_many :followers, through: :following_users

  VALID_USER_NAME_REGEX = /\A@[A-Za-z0-9]+\Z/

  validates :email, presence: true, uniqueness: true
  validates :full_name, presence: true,
              uniqueness: { case_sensitive: false},
              length: { minimum: 3, maximum: 50 }
  validates :user_name, presence: true,
              uniqueness: { case_sensitive: false},
              length: { minimum: 3, maximum: 25 },
              format: { with: VALID_USER_NAME_REGEX }

  before_save { self.email = email.downcase }

  def to_param
    user_name
  end
end

twitter_clone/app/controllers/application_controller.rb
# frozen_string_literal: true

# aplication controler handle parameters permitted by application
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[full_name user_name email])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[full_name user_name email])
  end
end

twitter_clone/app/controllers/home_controller.rb
# frozen_string_literal: true

# home controller, creates a redirection when logged in.
class HomeController < ApplicationController
  def index; end

  def about; end
end

twitter_clone/app/controllers/tweets_controller.rb
# frozen_string_literal: true

# tweet controller, creates a redirection when logged in to post tweets.
class TweetsController < ApplicationController
  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to show_user_path(current_user), notice: 'Your tweet was succesfully posted.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:tweet)
  end
end

twitter_clone/app/controllers/users_controller.rb
# frozen_string_literal: true

# defines methods for CRUD
class UsersController < ApplicationController
  before_action :set_user, only: %i[show followers followees follow unfollow follow_another_user]
  before_action :set_page, only: %i[show followers followees]

  USERS_PER_PAGE = 10
  TWEETS_PER_PAGE = 10

  def show
    @user_tweets = @user.tweet.offset(@page * TWEETS_PER_PAGE).limit(TWEETS_PER_PAGE).order(created_at: :desc)
  end

  def follow
    if current_user.followees.include?(@user)
      flash[:notice] = 'You are already following this user'
      redirect_to show_user_path(@user)
    else
      current_user.followees << @user
      redirect_to show_user_path(@user)
      flash[:notice] = 'You are now following this user'
    end
  end

  def unfollow
    current_user.followed_users.find_by(followee_id: @user.id).destroy
    redirect_to show_user_path(@user)
    flash[:notice] = 'You just unfollow this user'
  end

  def followers
    @user_followers = @user.followers.offset(@page * USERS_PER_PAGE).limit(USERS_PER_PAGE).order('full_name')
  end

  def followees
    @user_followees = @user.followees.offset(@page * USERS_PER_PAGE).limit(USERS_PER_PAGE).order('full_name')
  end

  def follow_another_user
    if current_user.followees.include?(@user)
      flash[:notice] = 'You are already following this user'
    else
      current_user.followees << @user
      flash[:notice] = 'You are now following this user'
    end
  end

  private

  def set_user
    @user = User.find_by(user_name: params[:id])
  end

  def set_page
    @page = params.fetch(:page, 0).to_i
  end
end

twitter_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

twitter_clone/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Twitter Clone', root_path, class: "navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
         
        <% if user_signed_in? %>     
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link"%>       
          </li>
          <li class="nav-item">
            <%= link_to "edit profile", edit_user_registration_path, class: "nav-link"%>       
          </li>
          <li class="nav-item">
            <%= link_to "sign out", destroy_user_session_path, method: :delete, class: "nav-link"%>       
          </li>
          <li class="nav-item">
            <div class="btn btn-info">
              <%= link_to "Tweet", new_tweet_path, class: "nav-link "%>       
            </div>
          </li>
          <li class="nav-item">
            <div>
              My Profile: 
              <%= link_to current_user.user_name, show_user_path(current_user), class:"nav-link fst-italic" %>      
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "sign up", new_user_registration_path, class: "nav-link"%>       
          </li>
          <li class="nav-item">
            <%= link_to "sign in", new_user_session_path, class: "nav-link"%>       
          </li>
        <% end %>
        
      </ul>
    </div>
  </div>
</nav>

twitter_clone/app/views/home/index.html.erb
<h1>i am index, welcome to my twitter clone</h1>

twitter_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter Clone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %>
    <div class="text-center mt-4">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>

twitter_clone/app/views/tweets/new.html.erb
<div class= "field text-center w-75 p-3">
  <%= form_with(model: @tweet) do |form| %>
    <% if @tweet.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@tweet.errors.count, "error") %> 
            prohibited this tweet from being posted:
        </h2>

        <ul>
          <% @tweet.errors.each do |error| %>
            <li>
              <%= error.full_message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group" >
      <strong>
        <%= form.label :tweet %>
      </strong>
      <%= form.text_area :tweet, class:"form-control form-control-lg" %>
    </div>
    <br>
  <div class="actions form-label">
      <%= form.submit :post, class:"btn btn-info" %>
    </div>
  <% end %>
</div>

twitter_clone/app/views/users/_followees_show.html.erb
<div class= "field text-center">
  <p>
    <%= followees_show.full_name %>
    (
      <%= link_to (followees_show.user_name), show_user_path(followees_show) %>
    )
  </p>
</div>

twitter_clone/app/views/users/_followers_show.html.erb
<div class="field text-center">
  <p>
    <%= followers_show.full_name %>
    (
      <%= link_to (followers_show.user_name), show_user_path(followers_show) %>
    )
  </p>
  <% if current_user.followees.include?(followers_show) && current_user != followers_show %>
    <h5>
      <%= button_to "Unfollow", unfollow_user_path(followers_show), class:'btn btn-info', method: "POST" %>
    </h5>
  <% else %>
    <% if current_user != followers_show %>
      <h5>
        <%= button_to "Follow", follow_user_path(followers_show), class:'btn btn-info', method: "POST"  %>
      </h5>    
    <% end %>
  <% end%>
</div>

twitter_clone/app/views/users/_tweets_show.html.erb
<div>
  <b>--------------------------------------------------</b>
  <br>
  this is: 
  <br>
  <strong>
    <%= (@user.full_name) %>, 
  </strong>
  <strong>
    <%= (@user.user_name) %> -
  </strong>
  <strong>
    <%= (tweets_show.created_at.strftime('%F')) %>
  </strong>
  <br>
  -------------------------
  <strong>
    <br>
    tweet:
    <br>
    </strong>
  <p>
  <%= tweets_show.tweet %>
  </p>
<div>

twitter_clone/app/views/users/follow_another_user.html.erb
<div class= "field text-center">
  <div class= "field text-center w-75 p-3">
    <%= form_with(url: follow_another_new_path(@user.user_name), method: 'post') do |form| %>
      <div class="field form-group" >
        <strong>
          <%= form.label :user_name %>
        </strong>
        <br>
        <%= form.text_area :user_name %>
      </div>
    <br>
    <div class="actions form-label">
        <%= form.submit 'follow user', class:"btn btn-info" %>
    </div>
    <% end %>
  </div>
</div>

twitter_clone/app/views/users/followees.html.erb
<div class="field text-center">
  <h1>
    <%= @user.user_name %>
    is following:
  </h1>
  <%= render partial: "followees_show", collection: @user_followees %>
  <br>
  <div>
    <%= link_to 'Follow another user', follow_another_path %>
  </div>
  <br>
  <div>
    <%= link_to 'Back', show_user_path, class:"btn btn-danger" %>
    <%= link_to "previous_page", followees_list_path(page: @page - 1), class:"btn btn-primary"%>
    <%= link_to "Next_page", followees_list_path(page: @page + 1), class:"btn btn-primary"%>
  </div>
</div>

twitter_clone/app/views/users/followers.html.erb
<div class="field text-center">
  <h1>
    <%= @user.user_name %> 
    is being followed by:
  </h1>
  <%= render partial: "followers_show", collection: @user_followers %>

  <div>
    <%= link_to 'Back', show_user_path, class:"btn btn-danger" %>
    <%= link_to "previous_page", followers_list_path(page: @page - 1), class:"btn btn-primary"%>
    <%= link_to "Next_page", followers_list_path(page: @page + 1), class:"btn btn-primary"%>
  </div>
</div>

twitter_clone/app/views/users/show.html.erb
<div class="field text-center">
  <section id="all-links">
    <h1>Tweets page</h1>
    <%= render partial: "tweets_show", collection: @user_tweets %>

    <% if @user.id == current_user.id %>
      <%= button_to "sign out", '/logout', method: :post %>
    <% elsif current_user.followees.include?(@user) %>
      <h5>
        <%= button_to "Unfollow", unfollow_user_path, class:'btn btn-info', method: "POST" %>
      </h5>
    <% else %>
      <h5>
        <%= button_to "Follow", follow_user_path,class:'btn btn-info', method: "POST"  %>
      </h5>
    <% end%>
    <br>
    <div>
      <%= link_to "previous_page", show_user_path(page: @page - 1), class:"btn btn-primary"%>
      <%= link_to "Next_page", show_user_path(page: @page + 1), class:"btn btn-primary"%>  
    </div>
    <div>
      <p class="card-text">
        <%= link_to (pluralize(@user.followers.count, "follower")), followers_list_path %>
      </p>
      <p class="card-text">
        <%= link_to (pluralize(@user.followees.count, "followee")), followees_list_path %>
      </p>
    </div>

  </section>

  <% if @user != current_user %>
    <%= link_to 'Back', show_user_path(current_user), class:"btn btn-danger" %>
  <% end %>
</div>